// Generated by karac for veil.wasm — TypeScript declarations for
// the browser-WASM glue module. DO NOT EDIT.

/** Trailing context argument passed to every host fn implementation. */
export interface HostCtx {
  readonly memory: WebAssembly.Memory;
  /** Decode a (ptr, len) UTF-8 string out of the module's linear memory. */
  readString(ptr: number | bigint, len: number | bigint): string;
}

/**
 * Host fn implementations (the `kara_host` import namespace).
 * i64/u64/isize/usize cross the boundary as bigint; every other
 * host-fn-legal scalar is a number; strings arrive as (ptr, len)
 * pairs — decode with `ctx.readString`.
 */
export interface HostImpls {
  /** `host fn read_src(dst: *const u8, len: i64)` */
  read_src(dst: number, len: bigint, ctx: HostCtx): void;
  /** `host fn put_pixels(ptr: *const u8, len: i64, w: i64, h: i64)` */
  put_pixels(ptr: number, len: bigint, w: bigint, h: bigint, ctx: HostCtx): void;
}

export interface InstantiateOpts {
  /** Pre-compiled module — bypasses the default loader. */
  module?: WebAssembly.Module;
  /** Raw module bytes — bypasses the default loader. */
  bytes?: BufferSource;
}

export interface KaraExports {
  _start(): void;
  process(op: bigint, sw: bigint, sh: bigint, x: bigint, y: bigint, w: bigint, h: bigint, s: bigint): void;
}

export interface KaraHandle {
  instance: WebAssembly.Instance;
  exports: WebAssembly.Exports & KaraExports;
  memory: WebAssembly.Memory;
}

/** Decode a (ptr, len) UTF-8 string out of the module's linear memory. */
export function readString(
  memory: WebAssembly.Memory,
  ptr: number | bigint,
  len: number | bigint,
): string;

/** Thrown by the WASI polyfill's proc_exit; run() swallows exit code 0. */
export class KaraExit extends Error {
  code: number;
  constructor(code: number);
}

/**
 * Compile + instantiate the module. Missing host fn implementations
 * throw before any wasm runs.
 */
export function instantiate(
  hostImpls: HostImpls,
  opts?: InstantiateOpts,
): Promise<KaraHandle>;

/**
 * Instantiate and run the program's entry point (`_start`). A clean
 * exit resolves normally; a nonzero exit code rejects with KaraExit.
 */
export function run(
  hostImpls: HostImpls,
  opts?: InstantiateOpts,
): Promise<KaraHandle>;
